import { branding } from '@shared/branding';
import React from 'react';

import { i18nService } from '@/services/i18n';

interface PrivacyDialogProps {
  onAccept: () => void;
  onReject: () => void;
}

function buildAgreement(lang: 'zh' | 'en'): string {
  const app = branding.appName;
  const company = lang === 'zh' ? branding.company.zh : branding.company.en;

  if (lang === 'en') {
    return `Welcome to ${app} (the "Platform"). The Platform is an internal AI office-collaboration assistant provided by ${company}. Please read and fully understand the following terms before use. By clicking "I have read and agree" or by using the Platform, you accept all of these terms.

1. About the service
1.1 The Platform is an internal office assistant that helps you with tasks such as document writing, data analysis, information retrieval, scheduling and email handling.
1.2 Model inference is provided through the company's internal gateway, and tasks run within the working environment on your own machine.

2. Acceptable use
2.1 You shall use the Platform only within the scope authorized by the company and for legitimate work purposes, complying with applicable laws and company policies.
2.2 You shall not use the Platform for any illegal activity, infringement of others' rights, or actions that endanger information security.
2.3 You are responsible for safeguarding your account and device.

3. Data and privacy
3.1 The Platform stores data locally first; sessions, configuration and memory are kept on your machine by default.
3.2 To perform AI tasks, relevant content is sent to the company's internal model gateway for processing. Do not enter personal sensitive information unrelated to work.
3.3 You must keep company trade secrets, client information and other confidential data confidential, and comply with company information-security and compliance requirements.

4. Permissions and safety
4.1 When performing operations involving files, commands or the network, the Platform will request your approval, limited to the designated working directory.
4.2 Please confirm the operation before approving, and handle high-risk operations with care.

5. Intellectual property
5.1 The intellectual property of the Platform and its software, interface and documentation belongs to ${company} or the respective rights holders.
5.2 Ownership of work products you create with the Platform follows the company's relevant policies.

6. Disclaimer
6.1 Content generated by the Platform is produced by AI models and may be inaccurate or incomplete. It is for reference only and does not constitute professional advice. Please verify before use.
6.2 To the extent permitted by law, ${company} is not liable for losses arising from use of the Platform beyond what the law requires.

7. Changes and termination
7.1 ${company} may update these terms as needed; updated terms take effect upon publication.
7.2 If you do not agree with these terms or their updates, please stop using the Platform.

8. Miscellaneous
8.1 These terms are governed by the company's management policies and applicable law.
8.2 For any questions about these terms, please contact the company's IT or compliance department.`;
  }

  return `欢迎使用${app}（以下简称“本平台”）。本平台由${company}提供，是一款面向公司内部的 AI 办公协同助手。在使用前，请您仔细阅读并充分理解本协议各条款。当您点击“我已阅读并同意”或开始使用本平台，即表示您已接受本协议的全部内容。

一、服务说明
1.1 本平台是部署于公司内部的智能办公助手，可协助您完成文档撰写、数据分析、信息检索、日程与邮件处理等办公任务。
1.2 本平台的模型推理通过公司内部网关提供，任务在您本机的工作环境中执行。

二、使用规范
2.1 您应在公司授权范围内、为正当办公目的使用本平台，遵守国家法律法规及公司各项规章制度。
2.2 您不得利用本平台从事任何违法违规、侵害他人合法权益或危害信息安全的活动。
2.3 您应妥善保管您的账号与设备，因您个人原因导致的信息泄露由您承担相应责任。

三、数据与隐私
3.1 本平台采用本地优先的数据存储方式，会话、配置与记忆默认保存在您本机。
3.2 为完成 AI 任务，相关内容会发送至公司内部模型网关进行处理；请勿在任务中输入与办公无关的个人敏感信息。
3.3 您应对涉及公司商业秘密、客户信息及其他保密数据的处理承担保密义务，遵守公司信息安全与合规要求。

四、权限与安全
4.1 本平台在执行涉及文件、命令或网络的操作时，会请求您的授权，操作范围限定在指定的工作目录内。
4.2 请您在授权前确认操作内容，对高风险操作审慎处理。

五、知识产权
5.1 本平台及其相关软件、界面与文档的知识产权归${company}或相应权利人所有。
5.2 您使用本平台生成的工作成果，其权利归属按公司相关规定执行。

六、免责声明
6.1 本平台生成的内容由 AI 模型产出，可能存在不准确或不完整之处，仅供参考，不构成任何专业意见或决策依据，请您在使用前自行核实。
6.2 在法律允许的范围内，因使用本平台造成的损失，${company}不承担超出法律规定的责任。

七、协议变更与终止
7.1 ${company}可根据业务与合规需要适时更新本协议，更新后的协议自公布之日起生效。
7.2 若您不同意本协议或其更新内容，请停止使用本平台。

八、其他
8.1 本协议的解释、适用及相关争议，适用公司相关管理规定及中华人民共和国法律。
8.2 如对本协议有任何疑问，请联系公司信息技术或合规部门。`;
}

const PrivacyDialog: React.FC<PrivacyDialogProps> = ({ onAccept, onReject }) => {
  const lang = i18nService.getLanguage();
  const agreement = buildAgreement(lang);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center modal-backdrop">
      <div
        className="modal-content w-full max-w-lg mx-4 bg-surface rounded-2xl shadow-modal overflow-hidden flex flex-col"
        style={{ maxHeight: '80vh' }}
      >
        {/* Header */}
        <div className="px-6 pt-6 pb-3 shrink-0">
          <h2 className="text-lg font-semibold text-foreground text-center">
            {i18nService.t('privacyDialogTitle')}
          </h2>
        </div>

        {/* Scrollable agreement body */}
        <div className="px-6 flex-1 overflow-y-auto">
          <p className="text-[13px] text-secondary leading-relaxed whitespace-pre-wrap">
            {agreement}
          </p>
        </div>

        {/* Buttons */}
        <div className="px-6 pb-6 pt-3 flex gap-3 shrink-0 border-t border-border">
          <button
            onClick={onReject}
            className="flex-1 px-4 py-2.5 rounded-xl text-sm font-medium text-secondary bg-surface-raised hover:opacity-80 transition-opacity"
          >
            {i18nService.t('privacyDialogReject')}
          </button>
          <button
            onClick={onAccept}
            className="flex-1 px-4 py-2.5 rounded-xl text-sm font-medium text-white bg-primary hover:bg-primary-hover transition-colors"
          >
            {i18nService.t('privacyDialogAccept')}
          </button>
        </div>
      </div>
    </div>
  );
};

export default PrivacyDialog;
